name: 'Naked & Inside Out'
favicon: null
layout_spectrum: 0.9392328984104097
typography_spectrum: 0.5619683794211596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.06554836151190102
  lightness: 0.7051472731400281
  saturation: 0.026147136697545648
  rhythmicContrast: 0.8218708990607411
purpose: []
